
services:
  master11:
    build: .
    container_name: master11
    hostname: master11
    ports:
      - "19870:9870"    
      - "18088:8088"    
      - "12181:2181"    
      - "19000:9000"    
    environment:
      - HADOOP_NODENAME=nn1
    volumes:
      - hadoop_data_master11:/opt/hadoop/hdfs
    networks:
      - hadoop_net
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'NameNode|DFSZKFailoverController|ResourceManager'"]      
      interval: 30s
      timeout: 10s
      retries: 25
      start_period: 10s

  master22:
    build: .
    container_name: master22
    hostname: master22
    ports:
      - "19871:9870"    
      - "18089:8088"    
      - "12182:2181"    
      - "19001:9000"    
    environment:
      - HADOOP_NODENAME=nn2
    volumes:
      - hadoop_data_master22:/opt/hadoop/hdfs
    networks:
      hadoop_net:
    depends_on:
      - master11
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'NameNode|DFSZKFailoverController|ResourceManager'"]      
      interval: 30s
      timeout: 10s
      retries: 25
      start_period: 10s

  master33:
    build: .
    container_name: master33
    hostname: master33
    ports:
      - "19872:9870"   
      - "18090:8088"    
      - "12183:2181"    
      - "19002:9000"    
    environment:
      - HADOOP_NODENAME=nn3
    volumes:
      - hadoop_data_master33:/opt/hadoop/hdfs
    networks:
      hadoop_net:
    depends_on:
      - master11
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'NameNode|DFSZKFailoverController|ResourceManager'"]      
      interval: 30s
      timeout: 10s
      retries: 25
      start_period: 10s

  worker11:
    build: .
    container_name: worker11
    hostname: worker11   
    volumes:
      - hadoop_data_worker1:/opt/hadoop/hdfs
    networks:
      hadoop_net:
    depends_on:
      master11:
        condition: service_healthy
      master22:
        condition: service_healthy
      master33:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'DataNode|NodeManager'"]
      interval: 30s
      timeout: 10s
      retries: 25

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=seif
      - POSTGRES_PASSWORD=seif
      - POSTGRES_DB=hive
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql-42.6.0.jar:/opt/hive/lib/postgresql-42.6.0.jar:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hadoop_net
    ports:
      - "5432:5432"

  metastore:
    build: .
    container_name: metastore
    hostname: metastore
    volumes:
      - ./ConfigHive:/opt/hive/conf
    environment:
      - SERVICE_TYPE=metastore
    networks:
      - hadoop_net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9083 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 25

  hiveserver:
    build: .
    container_name: hiveserver2
    hostname: hiveserver2
    volumes:
      - ./ConfigHive:/opt/hive/conf
      - ./etl_script.py:/home/hadoop/etl_script.py
    ports:
      - "10000:10000" 
      - "10002:10002"
    environment:
      - SERVICE_TYPE=hiveserver2
    networks:
      - hadoop_net
    depends_on:
      - metastore

volumes:
  hadoop_data_master11:
  hadoop_data_master22:
  hadoop_data_master33:
  hadoop_data_worker1:
  postgres_data:

networks:
  hadoop_net:
    driver: bridge